version: "3"
services:
  web:
    image: hc-vod-web
    volumes:
      - /home/chenyarong/docker/docker-web-dev/etc:/usr/local/etc
      - /home/chenyarong/docker/docker-web-dev/bin/boot.sh:/root/boot.sh
      - /data:/data
    ports:
      - 8089:80
    command: /root/boot.sh

