version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: c-nginx
    networks:
      - php_network
    ports:
      - 8080:80
    volumes:
      - ./wwwroot:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d

  php:
    build: 
      context: ./php-fpm
    container_name: c-php-fpm
    networks:
      - php_network
    volumes:
      - ./wwwroot:/var/www/html

networks:
  php_network:
    driver: bridge
