version: "3"
services:
  nginx:
    image: nginx
    container_name: hc-nginx
    # privileged: true 用于避免容器没有读取主机的挂载卷权限 
    privileged: true
    ports:
      - "80:80"
    working_dir: /data/wwwroot
    volumes:
      - ./etc/nginx/:/etc/nginx/
      # - ./logs/nginx:/var/log/nginx/
      # - /usr/local/etc/nginx:/etc/nginx/
      - /data/wwwroot/:/data/wwwroot/
      - /data/logs/:/data/logs/
    links:
      - phpfpm

  # php-fpm
  phpfpm:
    image: hc-php-fpm
    # privileged: true 用于避免容器没有读取主机的挂载卷权限 
    privileged: true
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: hc-fpm
    working_dir: /data/wwwroot
    volumes:
      - /data/wwwroot/:/data/wwwroot/
      - /data/ext/:/data/ext/
      - /data/logs/:/data/logs/

